wandb_version: 1

batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.05
lr_decay:
  desc: null
  value: 0.5
lr_decay_step:
  desc: null
  value: 10
num_epochs:
  desc: null
  value: 500
train_percentage:
  desc: null
  value: 0.8
criteria:
  desc: null
  value: nn.MSELoss()
optim:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722896809
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.17.5
      8:
      - 1
      - 5
      13: linux-x86_64
